export const ADDING_STORY = 'ADDING_STORY';
export const CARD_CLICKED = 'CARD_CLICKED';
export const CARD_UNCLICKED = 'CARD_UNCLICKED';
export const MAPCARD_CLICKED = 'MAPCARD_CLICKED';
export const SELECTED_STORY = 'SELECTED_STORY';
export const REMOVE_SELECTED_STORY = 'REMOVE_SELECTED_STORY';
